### ISSUE TITLE
Version 4.0.7 not building with Flutter 2.5.3(Dart 2.14) and IOS Platform

### ISSUE THREAD

**Issue by alefFSilva** [AgoraIO/Agora-Flutter-RTM-SDK#120]
I'm trying to run the version 4.0.7 with Flutter 2.5.3 but the building is not working on IOS platform.

I tried to run `flutter run -v` even with the repo example and it not worked.

```
 The following build commands failed:
               	Ld

/Users/alefferreiradasilva/Library/Developer/Xcode/DerivedData/Runner-dxjftvpgrxaileazurjwdwangrtm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/agora_rtc_engine.build/Objects-normal/arm64/B
               	inary/agora_rtc_engine normal arm64 (in target 'agora_rtc_engine' from project 'Pods')
               (1 failure)


/Users/alefferreiradasilva/Library/Developer/Xcode/DerivedData/Runner-cyxnyolzhttrtngroclanvavgkve/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/agora_rtc_engine.build/Objects-normal/a
                            rm64/Binary/agora_rtc_engine
                        ld: building for iOS Simulator, but linking in dylib built for iOS, file
                        '/Users/alefferreiradasilva/Dev/my-repos/Agora-Flutter-SDK/example/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64
                        clang: error: linker command failed with exit code 1 (use -v to see invocation)
                    
                    
[ +378 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 13.
[   +3 ms] "flutter run" took 31,994ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +139 ms] ensureAnalyticsSent: 138ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-BR)
    • Flutter version 2.5.3 at /Users/alefferreiradasilva/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alefferreiradasilva/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] VS Code (version 1.49.0)
    • VS Code at /Users/alefferreiradasilva/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • EEA83B75-1F95-40D4-B7D3-F7B3FACD788E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

**Comment by LichKing-2234** [comment]
Try to add these lines to your Podfile.
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Temporary exclude simulator arm64 to allow run app on simulator
    # https://developer.apple.com/forums/thread/656509
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 arm64"
    end
  end
end
```

**Comment by alefFSilva** [comment]
The problem was fixed with the latest Agora version, thanks!
