### ISSUE TITLE
AgoraRtmLocalInvitation.fromJson 解析数据时 `response`为`null`导致异常抛出

### ISSUE THREAD

**Issue by iBinbro** [AgoraIO/Agora-Flutter-RTM-SDK#96]
```
AgoraRtmRemoteInvitation.fromJson(Map<dynamic, dynamic> json)
      : calleeId = json['calleeId'],
        content = json['content'],
        response = json['response'],
        channelId = json['channelId'],
        state = json['state'];
```

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      new AgoraRtmRemoteInvitation.fromJson (package:agora_rtm/src/utils.dart:115:18)
#11 AgoraRtmClient._eventListener (package:agora_rtm/src/agora_rtm_client.dart:153:45)
```
`response`为null会导致异常，这里请都加上 null 判断处理

**Comment by LichKing-2234** [comment]
fixed
